version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: devopspulse-jenkins
    user: root
    privileged: true
    ports:
      - "8085:8080"
      - "50005:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: unless-stopped

volumes:
  jenkins-data:
